# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Practicing Ruby
email: gregory@practicingdeveloper.com
description: > # this means to ignore newlines until "baseurl:"
  The world's largest collection of lessons for experienced
  Ruby developers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://practicingruby.com" # the base hostname & protocol for your site
twitter_username: practicingdev
github_username:  practicingdeveloper

# Build settings
markdown: kramdown
